name: E2E UI

on: [pull_request]

permissions:
  contents: read
concurrency:
  group: e2e-ui-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    name: UI Test E2E
    services:
      verdaccio:
        image: verdaccio/verdaccio:6
        ports:
          - 4873:4873
        env:
          NODE_ENV: production
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Build application with Node 20
        uses: ./.github/actions/build-app
        with:
          node-version: 20
      - name: Test UI
        run: pnpm test:e2e:ui
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: videos
          path: /home/runner/work/verdaccio/verdaccio/e2e/ui/cypress/videos
