on:
  workflow_call:
    inputs:
      verdaccio-version:
        description: 'Verdaccio version to use'
        required: false
        default: 'latest'
        type: string

jobs:
  testVerdaccio:
    name: Test Verdaccio Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Publish
      uses: verdaccio/github-actions/publish@master # always latest by design 
      with:
        args: -d
        verdaccio-version: ${{ inputs.verdaccio-version }}
