on:
  workflow_call:
    inputs:
      verdaccio-version:
        description: 'Verdaccio version to use'
        required: false
        default: 'latest'
        type: string

jobs:
  testVerdaccio:
    name: Test Verdaccio Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Publish
      uses: verdaccio/github-actions/publish@master # always latest by design 
      with:
        args: -d
        verdaccio-version: ${{ inputs.verdaccio-version }}
